/*
 * Dually's legal copy, mirrored from the app.
 *
 * The mobile apps render these documents from the backend's
 * `/api/v1/user/privacy` and `/api/v1/user/terms-and-conditions` endpoints,
 * which store each document as one plain-text blob. That text is transcribed
 * here as structured blocks so the site can lay it out properly and so the
 * landing page has no runtime dependency on the API being up.
 *
 * Block types:
 *   h2   numbered top-level section       ("1. Information We Collect")
 *   h3   numbered subsection              ("1.1 Information You Provide to Us")
 *   p    paragraph, optionally `label`-ed ("Eligibility: ...")
 *   li   bullet within the preceding run of bullets
 *
 * Keep this in sync with the app whenever the documents change there.
 */

export const PRIVACY = {
  slug: 'privacy',
  title: 'Privacy Policy',
  // `updatedAt` on the backing API record.
  updated: 'December 30, 2024',
  intro:
    'How StreamWise LLC collects, uses, shares and protects your information when you use Dually.',
  blocks: [
  { type: "p", text: "StreamWise LLC (“we,” “us,” or “our”) is committed to protecting your privacy and ensuring that your personal information is handled in a safe and responsible manner. This Data Privacy Policy (“Policy”) describes how we collect, use, share, and protect your personal information when you use the Dually mobile application and associated services (the “Service”). By using our Service, you agree to the collection and use of information as outlined in this Policy. If you do not agree with this Policy, please do not use the Service." },
  { type: "h2", num: "1", text: "Information We Collect" },
  { type: "p", text: "We collect the following types of personal information:" },
  { type: "h3", num: "1.1", text: "Information You Provide to Us" },
  { type: "p", text: "When you create an account, use our Service, or interact with us, you may provide us with personal information, such as:" },
  { type: "p", label: "Account Information", text: "Name, email address, username, password, and profile picture." },
  { type: "p", label: "Payment Information", text: "Credit card details or payment account information (e.g., PayPal) if you use paid features or services." },
  { type: "p", label: "Content Information", text: "Information related to the live streams you create, including videos, comments, and messages exchanged during live chats." },
  { type: "p", label: "Communication Information", text: "Emails, feedback, or inquiries you send to our support team." },
  { type: "h3", num: "1.2", text: "Information We Automatically Collect" },
  { type: "p", text: "When you access or use the Service, we automatically collect certain information, including:" },
  { type: "p", label: "Device Information", text: "Device type, operating system, unique device identifiers, and mobile network information." },
  { type: "p", label: "Usage Data", text: "Information about how you interact with the Service, such as time spent on the app, features used, and actions taken." },
  { type: "p", label: "Log Data", text: "IP address, browser type, and the pages you visited before or after using the Service." },
  { type: "p", label: "Location Data", text: "Approximate geolocation data based on your IP address, with your consent." },
  { type: "h3", num: "1.3", text: "Information from Third Parties" },
  { type: "p", text: "We may collect information from third-party sources, including:" },
  { type: "li", text: "Social media accounts (e.g., if you log in via Google or Facebook)." },
  { type: "li", text: "Data from payment processors and advertising networks." },
  { type: "h2", num: "2", text: "How We Use Your Information" },
  { type: "p", text: "We use your personal information for the following purposes:" },
  { type: "h3", num: "2.1", text: "To Provide and Improve Our Services" },
  { type: "li", text: "To create and manage your account." },
  { type: "li", text: "To provide and personalize the streaming and live chat experience." },
  { type: "li", text: "To process payments and manage subscriptions." },
  { type: "li", text: "To maintain, enhance, and improve the app's functionality and user experience." },
  { type: "h3", num: "2.2", text: "To Communicate with You" },
  { type: "li", text: "To respond to your inquiries, feedback, or support requests." },
  { type: "li", text: "To send you important updates, notifications, and service-related messages." },
  { type: "h3", num: "2.3", text: "For Marketing and Promotions" },
  { type: "li", text: "To send you promotional emails and offers related to the Service." },
  { type: "li", text: "To provide personalized content, ads, and recommendations." },
  { type: "h3", num: "2.4", text: "For Legal and Compliance Purposes" },
  { type: "li", text: "To comply with applicable laws, regulations, and legal processes." },
  { type: "li", text: "To enforce our terms of service, protect our legal rights, and prevent fraud." },
  { type: "h2", num: "3", text: "Sharing of Your Information" },
  { type: "p", text: "We do not sell your personal information. However, we may share your information in the following circumstances:" },
  { type: "h3", num: "3.1", text: "With Service Providers" },
  { type: "p", text: "We may share your personal information with third-party service providers who perform functions on our behalf, including:" },
  { type: "li", text: "Payment processors (e.g., PayPal, Stripe) for handling payments." },
  { type: "li", text: "Cloud storage and hosting providers for data storage and security." },
  { type: "li", text: "Analytics providers for tracking and improving app performance." },
  { type: "h3", num: "3.2", text: "With Social Media Platforms" },
  { type: "p", text: "If you choose to log in using a social media platform (e.g., Google or Facebook), we may share information with those platforms in accordance with their privacy policies." },
  { type: "h3", num: "3.3", text: "For Legal Reasons" },
  { type: "p", text: "We may disclose your personal information if required to do so by law or if we believe that such action is necessary to:" },
  { type: "li", text: "Comply with legal obligations." },
  { type: "li", text: "Protect the rights, property, or safety of Dually, our users, or the public." },
  { type: "h2", num: "4", text: "Your Rights and Choices" },
  { type: "h3", num: "4.1", text: "Access, Update, or Delete Your Information" },
  { type: "p", text: "You can access, update, or delete your personal information at any time through your account settings or by contacting us at privacy@dually.app." },
  { type: "h3", num: "4.2", text: "Opting Out of Marketing Communications" },
  { type: "p", text: "You can opt out of receiving promotional emails by following the unsubscribe instructions in the email or by adjusting your account settings." },
  { type: "h3", num: "4.3", text: "Do Not Track Signals" },
  { type: "p", text: "We currently do not respond to “Do Not Track” signals sent by web browsers or other mechanisms." },
  { type: "h3", num: "4.4", text: "Data Retention" },
  { type: "p", text: "We retain your personal information for as long as necessary to provide the Service or as required by law. When your personal information is no longer needed, we will securely delete or anonymize it." },
  { type: "h2", num: "5", text: "Data Security" },
  { type: "p", text: "We implement industry-standard security measures to protect your personal information from unauthorized access, disclosure, alteration, or destruction. These measures include encryption, secure servers, and regular monitoring of our systems. However, no method of transmission over the internet or method of electronic storage is 100% secure, and we cannot guarantee absolute security. In the event of a data breach, we will notify you in accordance with applicable laws." },
  { type: "h2", num: "6", text: "International Data Transfers" },
  { type: "p", text: "If you are located outside of the United States, please note that your personal information may be transferred to and processed in the U.S., where data protection laws may differ from those in your country. By using our Service, you consent to such transfers and processing. For users in the European Union (EU), United Kingdom (UK), and California:" },
  { type: "li", text: "We comply with applicable data protection laws, including the General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA)." },
  { type: "li", text: "You have the right to access, correct, or delete your personal information and may request that we cease processing your data." },
  { type: "h2", num: "7", text: "Children’s Privacy" },
  { type: "p", text: "Our Service is not directed at children under the age of 13, and we do not knowingly collect personal information from children. If you believe that we have collected personal information from a child under the age of 13, please contact us at privacy@dually.app and we will take appropriate steps to delete the information." },
  { type: "h2", num: "8", text: "User-Generated Content Policy" },
  { type: "li", text: "Users must not post abusive, hateful, or inappropriate content. Violations will result in content removal and potential permanent account bans." },
  { type: "li", text: "A report button is available for users to flag objectionable content. Reported content will be reviewed within 24 hours, and necessary action will be taken. By using our app, you agree to follow these guidelines." },
  { type: "h2", num: "9", text: "Changes to This Policy" },
  { type: "p", text: "We may update this Data Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. We will notify you of any material changes by updating the \"Last Updated\" date at the top of this Policy or by sending a notification through the app." },
  { type: "h2", num: "10", text: "Contact Us" },
  { type: "p", text: "If you have any questions or concerns about this Privacy Policy, please contact us at:" },
  { type: "p", label: "Mobile Number", text: "+19432686565" },
  { type: "p", label: "Email", text: "privacy@dually.app" },
  ],
}

export const TERMS = {
  slug: 'terms',
  title: 'Terms & Conditions',
  // `updatedAt` on the backing API record.
  updated: 'December 30, 2024',
  intro:
    'The agreement that governs your use of the Dually app, services and website.',
  blocks: [
  { type: "p", text: "Welcome to Dually (“the Service”). These Terms and Conditions (“Terms”) govern your use of our app, services, and website (collectively, “Services”). By using Dually, you agree to be bound by these Terms." },
  { type: "h2", num: "1", text: "General Information" },
  { type: "p", label: "Service Provider", text: "Dually operates under the laws of the State of Georgia, United States. Users from other jurisdictions, including California (USA), the United Kingdom, and the European Union, should be aware of region-specific provisions in these Terms." },
  { type: "p", label: "Eligibility", text: "By using our Services, you confirm that you are at least 18 years old, or the legal age in your jurisdiction, and that you have the legal capacity to enter into these Terms." },
  { type: "h2", num: "2", text: "User Accounts" },
  { type: "p", label: "Registration", text: "To access certain features, you may be required to create an account. You must provide accurate and complete information." },
  { type: "p", label: "Responsibility", text: "You are responsible for maintaining the confidentiality of your account and password." },
  { type: "p", label: "Account Suspension", text: "We reserve the right to suspend or terminate any account that violates these Terms, or engages in unlawful or inappropriate behavior." },
  { type: "h2", num: "3", text: "Content and Intellectual Property" },
  { type: "p", label: "User-Generated Content", text: "You retain ownership of any content you upload to the Service (videos, images, etc.). By uploading, you grant Dually a worldwide, non-exclusive, royalty-free license to use, distribute, modify, and display this content within the Service." },
  { type: "p", label: "Prohibited Content", text: "Users are prohibited from uploading content that is illegal, harmful, offensive, or infringes on intellectual property rights." },
  { type: "p", label: "Intellectual Property Rights", text: "All other content provided by Dually (logos, trademarks, text, etc.) is owned by us or licensed to us and protected by copyright laws." },
  { type: "h2", num: "4", text: "Acceptable Use Policy" },
  { type: "p", text: "You agree to use the Service in compliance with all applicable local, state, federal, and international laws. You must not engage in unauthorized access, use of bots, scraping, or any activity that interferes with or disrupts the operation of the Service." },
  { type: "h2", num: "5", text: "Privacy" },
  { type: "p", text: "We take privacy seriously. Your personal information will be handled in accordance with our Privacy Policy, which complies with relevant laws including the California Consumer Privacy Act (CCPA), UK General Data Protection Regulation (GDPR), and EU GDPR." },
  { type: "p", label: "California Residents", text: "You have the right to request the deletion of your personal data and to know what personal data has been collected about you under the CCPA." },
  { type: "p", label: "UK & EU Residents", text: "You have the right to access, modify, delete, and restrict processing of your data in accordance with GDPR." },
  { type: "p", label: "Data Collection", text: "We collect data to improve the Service, including device information, usage data, and IP addresses. For more information, please see our Privacy Policy." },
  { type: "h2", num: "6", text: "Payment and Subscriptions" },
  { type: "p", label: "Subscription Plans", text: "Dually offers free and paid subscription plans. All paid subscriptions are billed on a recurring basis until canceled." },
  { type: "p", label: "Refunds", text: "Refunds are only issued under specific circumstances, such as technical failures directly caused by our Service. Otherwise, all payments are final." },
  { type: "p", label: "Changes to Pricing", text: "We reserve the right to change pricing and subscription terms, but we will notify you in advance of any changes." },
  { type: "h2", num: "7", text: "Limitation of Liability" },
  { type: "p", label: "No Warranty", text: "The Service is provided on an “as is” basis, and we disclaim all warranties, express or implied, including the accuracy, reliability, or availability of the Service." },
  { type: "p", label: "Liability", text: "To the maximum extent permitted by law, Dually will not be liable for any indirect, consequential, or incidental damages arising from the use or inability to use the Service, even if we have been advised of the possibility of such damages." },
  { type: "h2", num: "8", text: "Indemnification" },
  { type: "p", text: "You agree to indemnify and hold harmless Dually, its affiliates, and employees from any claims, damages, liabilities, and expenses arising from your use of the Service or violation of these Terms." },
  { type: "h2", num: "9", text: "Governing Law and Dispute Resolution" },
  { type: "p", label: "State of Georgia", text: "These Terms are governed by the laws of the State of Georgia, without regard to its conflict of law provisions." },
  { type: "p", label: "Dispute Resolution", text: "Any disputes will be resolved through binding arbitration in the State of Georgia, USA. If arbitration is not available, disputes may be brought in the state or federal courts located in Georgia." },
  { type: "p", label: "California Residents", text: "In accordance with California Civil Code Section 1789.3, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs." },
  { type: "p", label: "UK and EU Residents", text: "You have the right to pursue legal actions through your local courts under relevant consumer protection laws." },
  { type: "h2", num: "10", text: "Termination" },
  { type: "p", text: "We reserve the right to suspend or terminate your access to the Service for violation of these Terms or any behavior deemed harmful to the Service." },
  { type: "h2", num: "11", text: "Changes to the Terms" },
  { type: "p", text: "We reserve the right to modify these Terms at any time. You will be notified of any significant changes and your continued use of the Service after such changes constitutes acceptance of the revised Terms." },
  { type: "h2", num: "12", text: "Contact Information" },
  { type: "p", text: "For questions about these Terms, please contact us at:" },
  { type: "p", label: "Email", text: "support@dually.app" },
  { type: "p", label: "Mobile Number", text: "+19432686565" },
  { type: "h2", num: "13", text: "Miscellaneous" },
  { type: "p", label: "Severability", text: "If any provision of these Terms is found to be invalid, the remaining provisions will continue to be enforceable." },
  { type: "p", label: "Waiver", text: "Any failure by us to enforce a right or provision of these Terms will not be deemed a waiver of such rights." },
  ],
}

export const LEGAL_DOCS = { privacy: PRIVACY, terms: TERMS }
